CREATE PROCEDURE
@JSON NVARCHAR(MAX)
AS
BEGIN
    DECLARE @POSTID INT, @FILENAME VARCHAR(256)
    SELECT @POSTID=postid, @FILENAME=filename
    FROM OPENJSON(@JSON,'$')WITH(
        postid INT,
        filename VARCHAR(256)
    )

    DELETE FROM HYPERMEDIA WHERE POSTID=@POSTID
END