SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


create PROCEDURE [dbo].[POST_GETALL_ALLOWED]
@UID INT
AS
BEGIN
-- TO SEE ALL THE VISIBLE/ALLOWED POSTS OF A USER

-- declare @uid int = 1 

		--- ALL THE COLLECTIONS VISIBLE TO THE USER REQUESTER
		declare @all_colls JSON = (
			select '[' + STRING_AGG(CAST(ID AS VARCHAR), ',') + ']' from collections 	
			WHERE
			( --EXCLUSIVITY
					GETDATE()> ISNULL(EXCL_DATE_START,DATEADD(DAY,-1,GETDATE())) AND GETDATE() < ISNULL(EXCL_DATE_END,DATEADD(DAY,1,GETDATE())) --IF NULL, MAKE IT FROM YESTERDAY TILL TOMORROW
					AND
					(
						(@UID IN (SELECT VALUE FROM OPENJSON(VIEWERS,'$')) OR VIEWERS IS NULL OR VIEWERS = '[]') --VIEWER
					OR
						(@UID IN (SELECT VALUE FROM OPENJSON(CREATORS,'$')) OR CREATORS IS NULL OR CREATORS = '[]') -- CREATOR CAN BE VIEWER NO NEED TO SPECIFY
					)
				)OR OWNERID=@UID
		)

		exec post_get_map @uid=1, @COLLECTIONS_CHOSEN=@all_colls
END

GO
