SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

alter PROCEDURE [dbo].[PROFILE_GET_ALLOWEDPOST]
@UID INT, @PROFILE_ID int
AS
BEGIN
		--get the allowed posts and insert into a temp table

		DECLARE @ALLOWED_POSTS TABLE(
			ID INT,
			AUTHOR_ID INT,
			TITLE VARCHAR(500),
			COMMENT VARCHAR(MAX),
			DC DATETIME,
			DM DATETIME,
			LATITUDE FLOAT,
			LONGITUDE FLOAT,
			VISIBILITY_AREA_KM FLOAT,
			EXCL_DATE_START DATETIME,
			EXCL_DATE_END DATETIME,
			RECURRENT INT,
			COLLECTION_ID INT,
			VIEWERS NVARCHAR(MAX),
			order_id INT,
			post_id INT,
			COLOR VARCHAR(50),
			ICON VARCHAR(50),
			CATEGORY_NAME VARCHAR(50)
		);
		
		INSERT INTO @ALLOWED_POSTS (ID,AUTHOR_ID,TITLE,COMMENT,DC,DM,LATITUDE,LONGITUDE,VISIBILITY_AREA_KM,EXCL_DATE_START,EXCL_DATE_END,RECURRENT,COLLECTION_ID,VIEWERS,order_id,post_id,COLOR,ICON,CATEGORY_NAME) 
		EXEC POST_GETALL_ALLOWED @UID=@UID

		--filter by the user that we are viewing
		SELECT * FROM @ALLOWED_POSTS WHERE AUTHOR_ID = @PROFILE_ID 
	
END
GO