SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PROFILE_GETPOST_VIEWMODE]
@UID INT, @PROFILE_ID int
AS
BEGIN
-- TO SEE ALL THE VISIBLE/ALLOWED POSTS OF A USER

---		DECLARE @UID INT =3008
		--- ALL THE COLLECTIONS VISIBLE TO THE USER REQUESTER
		declare @all_colls NVARCHAR(MAX) = (
			select '[' + STRING_AGG(CAST(ID AS VARCHAR), ',') + ']' from collections 	
			WHERE
			( --EXCLUSIVITY
					GETDATE()> ISNULL(EXCL_DATE_START,DATEADD(DAY,-1,GETDATE())) AND GETDATE() < ISNULL(EXCL_DATE_END,DATEADD(DAY,1,GETDATE())) --IF NULL, MAKE IT FROM YESTERDAY TILL TOMORROW
					AND
					(
						(@UID IN (SELECT VALUE FROM OPENJSON(VIEWERS,'$')) OR VIEWERS IS NULL OR VIEWERS = '[]') --VIEWER
					OR
						(@UID IN (SELECT VALUE FROM OPENJSON(CREATORS,'$')) OR CREATORS IS NULL OR CREATORS = '[]') -- CREATOR CAN BE VIEWER NO NEED TO SPECIFY
					)
				)OR OWNERID=@UID
		)
		----------------
		--get the allowed posts and insert into a temp table

		DECLARE @ALLOWED_POSTS TABLE(
			ID INT,
			AUTHOR_ID INT,
			TITLE VARCHAR(500),
			COMMENT VARCHAR(MAX),
			DC DATETIME,
			DM DATETIME,
			LATITUDE FLOAT,
			LONGITUDE FLOAT,
			VISIBILITY_AREA_KM FLOAT,
			EXCL_DATE_START DATETIME,
			EXCL_DATE_END DATETIME,
			RECURRENT INT,
			COLLECTION_ID INT,
			VIEWERS NVARCHAR(MAX),
			order_id INT,
			post_id INT,
			COLOR VARCHAR(50),
			ICON VARCHAR(50),
			CATEGORY_NAME VARCHAR(50)
		);
		
		INSERT INTO @ALLOWED_POSTS (ID,AUTHOR_ID,TITLE,COMMENT,DC,DM,LATITUDE,LONGITUDE,VISIBILITY_AREA_KM,EXCL_DATE_START,EXCL_DATE_END,RECURRENT,COLLECTION_ID,VIEWERS,order_id,post_id,COLOR,ICON,CATEGORY_NAME) 
		exec post_get_map @uid=@uid, @COLLECTIONS_CHOSEN=@all_colls

		
		SELECT * FROM @ALLOWED_POSTS WHERE AUTHOR_ID = @PROFILE_ID --filter by the user that we are viewing
	
END

GO
