USE [master]
GO
/****** Object:  Database [GEOMEDIA]    Script Date: 25/03/2026 17:36:31 ******/
CREATE DATABASE [GEOMEDIA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GEOMEDIA', FILENAME = N'/var/opt/mssql/data/GEOMEDIA.mdf' , SIZE = 270336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GEOMEDIA_log', FILENAME = N'/var/opt/mssql/data/GEOMEDIA_log.ldf' , SIZE = 270336KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [GEOMEDIA] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
	EXEC [GEOMEDIA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GEOMEDIA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ARITHABORT OFF 
GO
ALTER DATABASE [GEOMEDIA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GEOMEDIA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GEOMEDIA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GEOMEDIA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GEOMEDIA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GEOMEDIA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GEOMEDIA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GEOMEDIA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GEOMEDIA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GEOMEDIA] SET  ENABLE_BROKER 
GO
ALTER DATABASE [GEOMEDIA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GEOMEDIA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GEOMEDIA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GEOMEDIA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GEOMEDIA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GEOMEDIA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GEOMEDIA] SET RECOVERY FULL 
GO
ALTER DATABASE [GEOMEDIA] SET  MULTI_USER 
GO
ALTER DATABASE [GEOMEDIA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GEOMEDIA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GEOMEDIA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GEOMEDIA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GEOMEDIA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GEOMEDIA] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'GEOMEDIA', N'ON'
GO
ALTER DATABASE [GEOMEDIA] SET QUERY_STORE = ON
GO
ALTER DATABASE [GEOMEDIA] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [GEOMEDIA]
GO
/****** Object:  Table [dbo].[COLLECTIONS]    Script Date: 25/03/2026 17:36:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COLLECTIONS]
(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TITLE] [varchar](50) NULL,
	[OWNERID] [int] NULL,
	[DESCRIPTION] [varchar](256) NULL,
	[DC] [datetime] NULL,
	[DM] [datetime] NULL,
	[CREATORS] [json] NULL,
	[VIEWERS] [json] NULL,
	[EXCL_DATE_START] [datetime] NULL,
	[EXCL_DATE_END] [datetime] NULL,
	[RECURRENT] [nvarchar](10) NULL,
	[REMOTE_POSTING] [bit] NULL,
	[SEQUENTIALS] [json] NULL,
	PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HYPERMEDIA]    Script Date: 25/03/2026 17:36:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HYPERMEDIA]
(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[POST_ID] [int] NULL,
	[FILENAME] [varchar](512) NULL,
	[FILEPATH] [varchar](512) NULL,
	[MIME_TYPE] [varchar](32) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INTERACTIONS]    Script Date: 25/03/2026 17:36:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INTERACTIONS]
(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[POST_ID] [int] NULL,
	[OWNERID] [int] NULL,
	[DC] [datetime] NULL,
	[DM] [datetime] NULL,
	[SCOPE] [varchar](20) NULL,
	PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOGS]    Script Date: 25/03/2026 17:36:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOGS]
(
	[ID] [int] NOT NULL,
	[MESSAGE] [nvarchar](1000) NULL,
	[SCOPE] [varchar](30) NULL,
	[DATELOG] [datetime] NULL,
	PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[POSTS]    Script Date: 25/03/2026 17:36:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[POSTS]
(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AUTHOR_ID] [int] NULL,
	[TITLE] [varchar](50) NULL,
	[COMMENT] [varchar](max) NULL,
	[DC] [datetime] NULL,
	[DM] [datetime] NULL,
	[LATITUDE] [float] NULL,
	[LONGITUDE] [float] NULL,
	[EXCLUSIVITY] [bit] NULL,
	[VISIBILITY_AREA_KM] [int] NULL,
	[EXCL_DATE_START] [datetime] NULL,
	[EXCL_DATE_END] [datetime] NULL,
	[VIEWERS] [json] NULL,
	[RECURRENT] [nchar](10) NULL,
	PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REPORTS]    Script Date: 25/03/2026 17:36:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REPORTS]
(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [int] NULL,
	[MOTIVE] [varchar](1200) NULL,
	[POSTID] [int] NULL,
	[DC] [datetime] NULL,
	[KIND] [varchar](10) NULL,
	[PROCESSED] [bit] NULL,
	PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 25/03/2026 17:36:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS]
(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERNAME] [varchar](50) NULL,
	[PASSWORD] [nvarchar](256) NOT NULL,
	[EMAIL] [varchar](128) NULL,
	[NAME] [varchar](30) NULL,
	[SURNAME] [varchar](30) NULL,
	[DC] [datetime] NULL,
	[DM] [datetime] NULL,
	[PROFILE_PICTURE] [nvarchar](max) NULL,
	[LASTIP] [nvarchar](max) NULL,
	[OTPCODE] [varchar](6) NULL,
	[EMAIL_VERIFIED] [bit] NULL,
	[LASTHEADERS] [nvarchar](max) NULL,
	[OTPDATE] [datetime] NULL,
	PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
	UNIQUE NONCLUSTERED 
(
	[USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[COLLECTIONS] ADD  DEFAULT (getdate()) FOR [DM]
GO
ALTER TABLE [dbo].[INTERACTIONS] ADD  DEFAULT (getdate()) FOR [DM]
GO
ALTER TABLE [dbo].[LOGS] ADD  DEFAULT (getdate()) FOR [DATELOG]
GO
ALTER TABLE [dbo].[POSTS] ADD  DEFAULT (getdate()) FOR [DM]
GO
ALTER TABLE [dbo].[USERS] ADD  DEFAULT (getdate()) FOR [DM]
GO
ALTER TABLE [dbo].[USERS] ADD  DEFAULT (NULL) FOR [PROFILE_PICTURE]
GO
ALTER TABLE [dbo].[USERS] ADD  DEFAULT ((0)) FOR [EMAIL_VERIFIED]
GO
ALTER TABLE [dbo].[COLLECTIONS]  WITH CHECK ADD FOREIGN KEY([OWNERID])
REFERENCES [dbo].[USERS] ([ID])
GO
ALTER TABLE [dbo].[HYPERMEDIA]  WITH CHECK ADD FOREIGN KEY([POST_ID])
REFERENCES [dbo].[POSTS] ([ID])
GO
ALTER TABLE [dbo].[INTERACTIONS]  WITH CHECK ADD FOREIGN KEY([OWNERID])
REFERENCES [dbo].[USERS] ([ID])
GO
ALTER TABLE [dbo].[INTERACTIONS]  WITH CHECK ADD FOREIGN KEY([POST_ID])
REFERENCES [dbo].[POSTS] ([ID])
GO
ALTER TABLE [dbo].[POSTS]  WITH CHECK ADD FOREIGN KEY([AUTHOR_ID])
REFERENCES [dbo].[USERS] ([ID])
GO
ALTER TABLE [dbo].[REPORTS]  WITH CHECK ADD FOREIGN KEY([POSTID])
REFERENCES [dbo].[POSTS] ([ID])
GO
ALTER TABLE [dbo].[REPORTS]  WITH CHECK ADD FOREIGN KEY([USERID])
REFERENCES [dbo].[USERS] ([ID])
GO
/****** Object:  StoredProcedure [dbo].[AUTH_CHECK_OTP]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE  PROCEDURE [dbo].[AUTH_CHECK_OTP]
	@JSON NVARCHAR(MAX)
AS
BEGIN

	IF EXISTS(SELECT *
	FROM USERS
	WHERE USERNAME=JSON_VALUE(@JSON,'$.USERNAME') AND OTPCODE = JSON_VALUE(@JSON,'$.OTP')
		AND DATEDIFF(hour,OTPDATE,GETDATE())<1 --OTP generated within an hour
    )
    BEGIN
		SELECT 1 AS AUTH, ID AS UID, *
		FROM USERS
		WHERE USERNAME= JSON_VALUE(@JSON,'$.USERNAME')
		UPDATE USERS SET EMAIL_VERIFIED = 1 WHERE USERNAME= JSON_VALUE(@JSON,'$.USERNAME')
	END
    ELSE -- TODO: METADATA IP, TO LOG AND SEND BACK
    BEGIN
		SELECT 0 AS AUTH
	END
END

GO
/****** Object:  StoredProcedure [dbo].[AUTH_LOGIN]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[AUTH_LOGIN]
	@JSON NVARCHAR(MAX)
AS
BEGIN

	DECLARE @USERNAME VARCHAR(50) = NULL,@EMAIL VARCHAR(128) = NULL, @PASSWORD NVARCHAR(256), @IP VARCHAR(200), @HEADERS NVARCHAR(MAX)

	SELECT @USERNAME=EMAIL, @EMAIL=EMAIL, @PASSWORD=PASSWORD, @IP=IP, @HEADERS=HEADERS
	FROM OPENJSON(@JSON,'$')WITH(
        EMAIL VARCHAR(128),
        PASSWORD NVARCHAR(256),
         IP VARCHAR(200),
        HEADERS NVARCHAR(MAX)
    )

	IF EXISTS (
        SELECT *
	FROM DBO.USERS
	WHERE (USERNAME=@USERNAME OR EMAIL=@EMAIL) AND [PASSWORD] = @PASSWORD
    )
    BEGIN
		SELECT 1 AS AUTH, ID AS UID, USERNAME, EMAIL, NAME, SURNAME
		FROM USERS
		WHERE (USERNAME=@USERNAME OR EMAIL=@EMAIL)

		UPDATE USERS SET LASTIP=@IP, LASTHEADERS=@HEADERS WHERE (USERNAME=@USERNAME OR EMAIL=@EMAIL)
	END
    ELSE
    BEGIN
		SELECT 0 AS AUTH, 'Invalid cretential' as MSG

	END



END


GO
/****** Object:  StoredProcedure [dbo].[AUTH_PSW_FORGOTTEN]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[AUTH_PSW_FORGOTTEN]
	@JSON VARCHAR(MAX)
AS
BEGIN
	DECLARE @OTP VARCHAR(6) = (SELECT CONVERT(varchar(255),(SELECT CAST(RAND()*1000000 AS INT))))

	UPDATE U SET OTPCODE =@OTP, OTPDATE=GETDATE()
	FROM USERS U
		INNER JOIN OPENJSON(@JSON,'$')WITH(
		USERNAMEMAIL VARCHAR(128)
	) J ON J.USERNAMEMAIL = U.EMAIL OR J.USERNAMEMAIL = U.USERNAME

	SELECT @OTP AS OTP, U.EMAIL
	--IN ORDER TO SEND THE OTP CODE VIA EMAIL
	FROM USERS U
		INNER JOIN OPENJSON(@JSON,'$')WITH(
		USERNAMEMAIL VARCHAR(128)
	) J ON J.USERNAMEMAIL = U.EMAIL OR J.USERNAMEMAIL = U.USERNAME

END
GO
/****** Object:  StoredProcedure [dbo].[AUTH_PSW_RESET]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[AUTH_PSW_RESET]
	@JSON NVARCHAR(MAX)
AS
BEGIN
	UPDATE U
	SET PASSWORD=J.NEWPASSWORD
	FROM USERS U
		INNER JOIN OPENJSON(@JSON,'$')WITH(
			USERNAMEMAIL VARCHAR(128),
			NEWPASSWORD NVARCHAR(512),
			OTP VARCHAR(6)
	) J ON (J.USERNAMEMAIL = U.EMAIL OR J.USERNAMEMAIL = U.USERNAME) AND J.OTP = U.OTPCODE

	IF @@ROWCOUNT>1
		SELECT 1 AS OK
	ELSE
	BEGIN
		SELECT 0 AS OK
	-- TODO: TO LOG THE REQUEST AS ATTACK/WRONG CODE
	END
END
GO
/****** Object:  StoredProcedure [dbo].[AUTH_SIGNIN]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[AUTH_SIGNIN]
	@JSON NVARCHAR(MAX)
AS
BEGIN

	DECLARE @USERNAME VARCHAR(50), @EMAIL VARCHAR(128),@PASSWORD NVARCHAR(256),@NAME VARCHAR(30)=NULL, @SURNAME VARCHAR(30)=NULL, @IP VARCHAR(200), @HEADERS NVARCHAR(MAX)

	SELECT @USERNAME=USERNAME, @EMAIL=EMAIL, @PASSWORD=PASSWORD, @NAME=NAME, @SURNAME=SURNAME
	FROM OPENJSON(@JSON,'$')WITH(
        USERNAME VARCHAR(50),
        EMAIL VARCHAR(128),
        PASSWORD NVARCHAR(256),
        NAME VARCHAR(30),
        SURNAME VARCHAR(30),
        IP VARCHAR(200),
        HEADERS NVARCHAR(MAX)
    )

	IF NOT EXISTS(
        SELECT *
	FROM USERS
	WHERE [EMAIL]=@EMAIL OR USERNAME = @USERNAME  --TODO: AND AUTH OK (in order to resend the otp)
    )
    BEGIN

		DECLARE @OTP VARCHAR(6) = (SELECT CONVERT(varchar(255),(SELECT CAST(RAND()*1000000 AS INT))))
		INSERT INTO USERS
			(EMAIL, USERNAME, NAME, SURNAME, DC, DM,[PASSWORD],OTPCODE, OTPDATE, LASTIP,LASTHEADERS)
		VALUES(@EMAIL, @USERNAME, @NAME, @SURNAME, GETDATE(), GETDATE(), @PASSWORD, @OTP, GETDATE(), @IP, @HEADERS);

		SELECT @OTP AS OTP, 2 AS AUTH, 'pending otp' as MSG
	END
    ELSE
    BEGIN
		SELECT 0 AS AUTH, 'Username or email already taken' as MSG
	END
END


GO
/****** Object:  StoredProcedure [dbo].[COLLECTIONS_GET]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[COLLECTIONS_GET]
	@UID INT,
	@MODE CHAR(1)
-- R (reading/viewing post), W (writing) to check if creator
AS
BEGIN

	IF(@MODE='W')
	BEGIN
		SELECT *
		FROM COLLECTIONS
		WHERE 
		( --EXCLUSIVITY
			GETDATE()> ISNULL(EXCL_DATE_START,DATEADD(DAY,-1,GETDATE())) AND GETDATE() < ISNULL(EXCL_DATE_END,DATEADD(DAY,1,GETDATE())) --IF NULL, MAKE IT FROM YESTERDAY TILL TOMORROW
			AND
			(@UID IN (SELECT VALUE
			FROM OPENJSON(CREATORS,'$')) OR CREATORS IS NOT NULL)
		)OR OWNERID=@UID
	END
	ELSE IF(@MODE='R')
	BEGIN
		SELECT *
		FROM COLLECTIONS
		WHERE 
		( --EXCLUSIVITY
			GETDATE()> ISNULL(EXCL_DATE_START,DATEADD(DAY,-1,GETDATE())) AND GETDATE() < ISNULL(EXCL_DATE_END,DATEADD(DAY,1,GETDATE())) --IF NULL, MAKE IT FROM YESTERDAY TILL TOMORROW
			AND
			(
				(@UID IN (SELECT VALUE
			FROM OPENJSON(VIEWERS,'$')) OR VIEWERS IS NOT NULL) --VIEWER
			OR
			(@UID IN (SELECT VALUE
			FROM OPENJSON(CREATORS,'$')) OR CREATORS IS NOT NULL) -- CREATOR CAN BE VIEWER NO NEED TO SPECIFY
			)
		)OR OWNERID=@UID
	END

END
GO
/****** Object:  StoredProcedure [dbo].[COLLECTIONS_MERGE]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[COLLECTIONS_MERGE]
	@JSON NVARCHAR(MAX)
AS
BEGIN

	MERGE INTO COLLECTIONS AS target
    USING (
        SELECT *
	FROM OPENJSON(@json)
        WITH (
            ID INT,
            TITLE VARCHAR(50),
            OWNERID INT,
            DESCRIPTION VARCHAR(256),
            CREATORS NVARCHAR(MAX),
            VIEWERS NVARCHAR(MAX),
            EXCL_DATE_START DATETIME,
            EXCL_DATE_END DATETIME,
            RECURRENT NVARCHAR(20),
            REMOTE_POSTING BIT,
            SEQUENTIALS NVARCHAR(MAX)
        )
    ) AS source
    ON target.ID = source.ID

    WHEN MATCHED THEN
        UPDATE SET
            TITLE = source.TITLE,
            OWNERID = source.OWNERID,
            DESCRIPTION = source.DESCRIPTION,
            DM = GETDATE(),
            CREATORS = source.CREATORS,
            VIEWERS = source.VIEWERS,
            EXCL_DATE_START = source.EXCL_DATE_START,
            EXCL_DATE_END = source.EXCL_DATE_END,
            RECURRENT = source.RECURRENT,
            REMOTE_POSTING = source.REMOTE_POSTING,
            SEQUENTIALS = source.SEQUENTIALS

    WHEN NOT MATCHED THEN
        INSERT (
            TITLE, OWNERID, DESCRIPTION, DC,DM,
            CREATORS, VIEWERS, EXCL_DATE_START, EXCL_DATE_END,
            RECURRENT,  REMOTE_POSTING,
            SEQUENTIALS
        )
        VALUES (
            source.TITLE, source.OWNERID, source.DESCRIPTION, GETDATE(),GETDATE(),
            source.CREATORS, source.VIEWERS, source.EXCL_DATE_START, source.EXCL_DATE_END,
            source.RECURRENT,source.REMOTE_POSTING,
            source.SEQUENTIALS
        );

END
GO
/****** Object:  StoredProcedure [dbo].[HPMEDIA_GETFILES]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[HPMEDIA_GETFILES]
	@POSTID INT
AS
BEGIN
	SELECT *
	FROM HYPERMEDIA
	WHERE POST_ID=@POSTID
END
GO
/****** Object:  StoredProcedure [dbo].[HPMEDIA_MERGEFILE]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE procedure [dbo].[HPMEDIA_MERGEFILE]
	@FILESNAME_ATTACHED NVARCHAR(MAX),
	@POSTID INT
AS
BEGIN
	BEGIN TRY

        MERGE HYPERMEDIA AS target
            USING (
                SELECT *
	FROM OPENJSON(@FILESNAME_ATTACHED)
                WITH (
                    filepath NVARCHAR(500),
                    filename NVARCHAR(255),
                    mimetype VARCHAR(32),
                    post_id INT
                )
	WHERE filename IS NOT NULL
            ) AS source
            ON  target.FILENAME = source.filename
		AND target.POST_ID = source.post_id

            WHEN NOT MATCHED BY TARGET THEN
                INSERT (FILEPATH, FILENAME,  POST_ID, MIME_TYPE)
                VALUES (source.filepath, source.filename,  source.post_id,source.mimetype)

            WHEN NOT MATCHED BY SOURCE
            AND target.POST_ID IN (
                SELECT POST_ID
	FROM OPENJSON(@FILESNAME_ATTACHED) WITH (POST_ID INT)
            )
            THEN DELETE;

        SELECT 1 AS OK
    END TRY
    BEGIN CATCH
        SELECT 0 AS OK, ERROR_MESSAGE() AS MSG
    END CATCH

END
GO
/****** Object:  StoredProcedure [dbo].[LOG_WRITE]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[LOG_WRITE]
	@MESSAGE NVARCHAR(1000),
	@SCOPE VARCHAR(30) ='DEBUG'
AS
BEGIN
	INSERT INTO LOGS
		(MESSAGE,SCOPE)
	VALUES
		(@MESSAGE, @SCOPE)

END
GO
/****** Object:  StoredProcedure [dbo].[POST_DELETE]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[POST_DELETE]
	@POSTID INT,
	@PASSWORD VARCHAR(128)
AS
BEGIN

	DELETE FROM POSTS  WHERE ID=@POSTID AND EXISTS (
        SELECT *
		FROM USERS
		WHERE ID = AUTHOR_ID AND PASSWORD=@PASSWORD
    )

	DECLARE @MSG NVARCHAR(1000)

	IF @@ROWCOUNT > 0
    BEGIN
		SELECT 1 AS OK
		SET @MSG =  CONCAT('DELETED POST', CAST(@POSTID AS VARCHAR(200)))
	END
    ELSE
    BEGIN
		SELECT 0 as OK
		SET @MSG =  CONCAT('CANNOT DELETE POST, WRONG PSW OR POSTID: ', CAST(@POSTID AS VARCHAR(200)), @PASSWORD)
	END

	EXEC LOG_WRITE @MESSAGE = @MSG, @SCOPE='POST_DELETE'


END





GO
/****** Object:  StoredProcedure [dbo].[POST_GET_COLLECTION]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[POST_GET_COLLECTION]
	@COLLECTION_ID INT
AS
BEGIN
	SELECT *
	FROM POSTS
--WHERE COLLECTION_ID =@COLLECTION_ID
END
GO
/****** Object:  StoredProcedure [dbo].[POST_GET_FULLPOST]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[POST_GET_FULLPOST]
	@JSON NVARCHAR(MAX)
AS
BEGIN
	SELECT *
	FROM POSTS
	WHERE ID=JSON_VALUE(@JSON,'$.postid')
--- TODO: save the entry in the reaction with scope  'view'
END
GO
/****** Object:  StoredProcedure [dbo].[POST_GET_MAP]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[POST_GET_MAP]
	@UID INT,
	@COLLECTIONS_CHOSEN JSON=NULL
AS
BEGIN

	SELECT *
	FROM POSTS
	WHERE 
	VIEWERS IS NULL OR @UID IN (
		SELECT VALUE
		FROM OPENJSON(VIEWERS,'$')
	)
		AND
		GETDATE()> ISNULL(EXCL_DATE_START,DATEADD(DAY,-1,GETDATE())) AND GETDATE() < ISNULL(EXCL_DATE_END,DATEADD(DAY,1,GETDATE()))
--IF NULL, MAKE IT FROM YESTERDAY TILL TOMORROW
-- TODO: CHECK THE COLLECTIONS IF ENABLED TO THE USERS
-- NB: THE VISIBILITY_AREA_KM FILTER IS MADE ON BACKEND OF THE SERVER


END

GO
/****** Object:  StoredProcedure [dbo].[POST_MERGE]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[POST_MERGE]
	@POST_CONTENT NVARCHAR(MAX)
AS
BEGIN
	BEGIN TRANSACTION T1
	BEGIN TRY

          DECLARE @Result TABLE (
		ID INT
        );

        MERGE INTO POSTS AS T
        USING (
            SELECT
		JJ.ID,
		JJ.AUTHOR_ID,
		JJ.TITLE,
		JJ.COMMENT,
		JJ.LATITUDE,
		JJ.LONGITUDE,
		JJ.EXCLUSIVITY,
		JJ.VISIBILITY_AREA_KM,
		DATE_EXL.DATE_START,
		DATE_EXL.DATE_END,
		JJ.VIEWERS,
		DATE_EXL.RECURRENT
	FROM OPENJSON(@POST_CONTENT,'$') WITH(
                ID INT,
                AUTHOR_ID INT,
                TITLE VARCHAR(50),
                COMMENT VARCHAR(MAX),
                MEDIA_B64 NVARCHAR(MAX),
                MEDIATYPE VARCHAR(100),
                MEDIAFILENAME VARCHAR(300),
                LATITUDE FLOAT,
                LONGITUDE FLOAT,
                VISIBILITY_AREA_KM INT,
                EXCLUSIVITY NVARCHAR(MAX) AS JSON,
                VIEWERS JSON                
            ) JJ OUTER APPLY OPENJSON(EXCLUSIVITY,'$.DATERANGE')WITH(
                DATE_START DATETIME,
                DATE_END DATETIME,
                RECURRENT CHAR(10)
            ) DATE_EXL
	WHERE TITLE IS NOT NULL

        ) AS S
        ON T.ID = S.ID

        WHEN MATCHED THEN
            UPDATE SET
                    T.TITLE = ISNULL(S.TITLE,T.TITLE),
                    T.COMMENT = ISNULL(S.COMMENT,T.COMMENT),
                    T.DM = GETDATE(),
                    T.LATITUDE = ISNULL(S.LATITUDE,T.LATITUDE),
                    T.LONGITUDE = ISNULL(S.LONGITUDE,T.LONGITUDE),
                    T.VISIBILITY_AREA_KM = ISNULL(S.VISIBILITY_AREA_KM,T.VISIBILITY_AREA_KM),
                    T.EXCL_DATE_START = ISNULL(S.DATE_START,T.EXCL_DATE_START),
                    T.EXCL_DATE_END = ISNULL(S.DATE_END,T.EXCL_DATE_END),
                    T.VIEWERS = ISNULL(S.VIEWERS,T.VIEWERS),
                    T.RECURRENT = ISNULL(S.RECURRENT,T.RECURRENT)




        WHEN NOT MATCHED THEN
            INSERT (
                AUTHOR_ID, TITLE, COMMENT, DC, DM,
                LATITUDE, LONGITUDE, 
                VISIBILITY_AREA_KM,
                EXCL_DATE_START,
                EXCL_DATE_END,
                VIEWERS,RECURRENT
                
            )
            VALUES (
                 S.AUTHOR_ID, S.TITLE, S.COMMENT, GETDATE(), GETDATE(),
                S.LATITUDE, S.LONGITUDE,
                S.VISIBILITY_AREA_KM,
                S.DATE_START,
                S.DATE_END,
                S.VIEWERS,
                S.RECURRENT
            )

        OUTPUT inserted.ID
        INTO @Result;

        COMMIT TRANSACTION T1;
        SELECT ID AS ID, 1 AS OK
	FROM @Result;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION T1;
        SELECT -1 AS ID, 0 AS OK, ERROR_MESSAGE() AS MSG
    END CATCH
END;

GO
/****** Object:  StoredProcedure [dbo].[PROFILE_EditInfo]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PROFILE_EditInfo]
	@JSON NVARCHAR(MAX)
AS
BEGIN
	UPDATE U
	SET
	 U.USERNAME  = ISNULL(JJ.USERNAME , U.USERNAME)
	,U.PASSWORD  = ISNULL(JJ.PASSWORD ,U.PASSWORD)
	,U.EMAIL  = ISNULL(JJ.EMAIL ,U.EMAIL)
	,U.NAME  = ISNULL(JJ.NAME ,U.NAME)
	,U.SURNAME  = ISNULL(JJ.SURNAME ,U.SURNAME)
	,U.PROFILE_PICTURE  = ISNULL(JJ.PROFILE_PICTURE ,U.PROFILE_PICTURE)
	,U.DM = GETDATE()
	FROM USERS U
		INNER JOIN OPENJSON(@JSON,'$.INFO') WITH(
		UID INT
		,USERNAME VARCHAR(50)
		,PASSWORD NVARCHAR(512)
		,EMAIL VARCHAR(128)
		,NAME VARCHAR(30)
		,SURNAME VARCHAR(30)
		,PROFILE_PICTURE NVARCHAR(MAX)
	) JJ ON JJ.UID = U.ID

	SELECT
		ID AS UID,
		USERNAME
	, PASSWORD
	, EMAIL
	, NAME
	, SURNAME
	FROM USERS
	WHERE ID = (
		SELECT JSON_VALUE(@JSON,'$.INFO.UID')
	)

END
GO
/****** Object:  StoredProcedure [dbo].[PROFILE_GetPFP]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PROFILE_GetPFP]
	@JSON NVARCHAR(MAX)
AS
BEGIN
	SELECT
		PROFILE_PICTURE
	FROM DBO.USERS
	WHERE USERNAME = JSON_VALUE(@JSON, '$.USERNAME')

END
GO
/****** Object:  StoredProcedure [dbo].[REPORT_NEW]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[REPORT_NEW]
	@JSON NVARCHAR(MAX)
AS
BEGIN
	INSERT INTO REPORTS
		(USERID,MOTIVE,POSTID,DC,KIND,PROCESSED)
	SELECT uid, motive, postid, getdate(), kind, 0
	FROM OPENJSON(@JSON,'$')WITH(
		postid int,
		uid int, 
		motive varchar(1200),
		kind varchar(10)
	)
	WHERE NOT EXISTS( --JUST ONE REPORT FOR POST&USER :: A UNIQUE KEY WOULD DO THE SAME EFFECT BUT NAH
		SELECT *
	FROM REPORTS
	WHERE USERID=uid AND POSTID=postid
	)

END
GO
/****** Object:  StoredProcedure [dbo].[USERS_LIST]    Script Date: 25/03/2026 17:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USERS_LIST]
AS
BEGIN
	SELECT ID AS UID, USERNAME, NAME, SURNAME, PROFILE_PICTURE
	FROM USERS
	WHERE EMAIL_VERIFIED=1
END
GO
USE [master]
GO
ALTER DATABASE [GEOMEDIA] SET  READ_WRITE 
GO
