USE [master]
GO
/****** Object:  Database [GEOMEDIA]    Script Date: 08/04/2025 17:08:23 ******/
CREATE DATABASE [GEOMEDIA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GEOMEDIA', FILENAME = N'/var/opt/mssql/data/GEOMEDIA.mdf' , SIZE = 139264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GEOMEDIA_log', FILENAME = N'/var/opt/mssql/data/GEOMEDIA_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [GEOMEDIA] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GEOMEDIA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GEOMEDIA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ARITHABORT OFF 
GO
ALTER DATABASE [GEOMEDIA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GEOMEDIA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GEOMEDIA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GEOMEDIA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GEOMEDIA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GEOMEDIA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GEOMEDIA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GEOMEDIA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GEOMEDIA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GEOMEDIA] SET  ENABLE_BROKER 
GO
ALTER DATABASE [GEOMEDIA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GEOMEDIA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GEOMEDIA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GEOMEDIA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GEOMEDIA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GEOMEDIA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GEOMEDIA] SET RECOVERY FULL 
GO
ALTER DATABASE [GEOMEDIA] SET  MULTI_USER 
GO
ALTER DATABASE [GEOMEDIA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GEOMEDIA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GEOMEDIA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GEOMEDIA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GEOMEDIA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GEOMEDIA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'GEOMEDIA', N'ON'
GO
ALTER DATABASE [GEOMEDIA] SET QUERY_STORE = ON
GO
ALTER DATABASE [GEOMEDIA] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [GEOMEDIA]
GO
/****** Object:  Table [dbo].[POSTS]    Script Date: 08/04/2025 17:08:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[POSTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AUTHOR] [varchar](50) NULL,
	[TITLE] [varchar](50) NULL,
	[COMMENT] [varchar](max) NULL,
	[MEDIATYPE] [varchar](100) NULL,
	[MEDIADATA] [nvarchar](max) NULL,
	[POSTDATETIME] [datetime] NULL,
	[LATITUDE] [float] NULL,
	[LONGITUDE] [float] NULL,
	[MEDIAFILENAME] [varchar](300) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 08/04/2025 17:08:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERNAME] [varchar](50) NOT NULL,
	[PASSWORD] [nvarchar](256) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[POSTS]  WITH CHECK ADD FOREIGN KEY([AUTHOR])
REFERENCES [dbo].[USERS] ([USERNAME])
GO
/****** Object:  StoredProcedure [dbo].[DELETEPOST]    Script Date: 08/04/2025 17:08:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[DELETEPOST]
@POSTID INT, @USER VARCHAR(50), @PASSWORD VARCHAR(128)
AS
BEGIN
	
	IF EXISTS (SELECT * FROM USERS WHERE USERNAME=@USER AND PASSWORD=@PASSWORD)
	BEGIN
		DELETE FROM POSTS WHERE ID=@POSTID	AND AUTHOR=@USER
		SELECT 1 AS ESITO
	END
	ELSE
	BEGIN
		SELECT 0 AS ESITO
	END
	
	
	

END




GO
/****** Object:  StoredProcedure [dbo].[DOLOGIN]    Script Date: 08/04/2025 17:08:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DOLOGIN]
@USERNAME VARCHAR(50), @PASSWORD NVARCHAR(256), @NEWUSER BIT
AS
BEGIN
	
	DECLARE @EXISTING_USER INT = ISNULL((SELECT ISNULL(ID,0) FROM USERS WHERE USERNAME=@USERNAME AND PASSWORD=@PASSWORD),0)
	--SELECT @EXISTING_USER
	
	IF(@NEWUSER =1 AND @EXISTING_USER=0) --CREATE
	BEGIN
		INSERT INTO USERS (USERNAME,PASSWORD)
		VALUES (@USERNAME,@PASSWORD)
		SELECT 1 AS ESITO
	END
	ELSE
	BEGIN
		IF (@EXISTING_USER>0)
	    BEGIN
	        SELECT 1 AS ESITO
	    END
	    ELSE
	    BEGIN 
	        SELECT 0 AS ESITO
	    END
	END
	
    

END

GO
/****** Object:  StoredProcedure [dbo].[GETMEDIAPOST]    Script Date: 08/04/2025 17:08:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GETMEDIAPOST]
@POSTID INT
AS
BEGIN
	SELECT MEDIADATA FROM POSTS WHERE ID=@POSTID
END

GO
/****** Object:  StoredProcedure [dbo].[GETPOSTS]    Script Date: 08/04/2025 17:08:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GETPOSTS]
@LATITUDE FLOAT=NULL, @LONGITUDE FLOAT=NULL, @USERNAME VARCHAR(50)=NULL
AS
BEGIN
	
	
	
	IF(@USERNAME IS NULL OR @USERNAME='NULL')
	BEGIN
	SELECT  ID, AUTHOR, TITLE, COMMENT, MEDIATYPE, POSTDATETIME, LATITUDE, LONGITUDE, MEDIAFILENAME FROM POSTS
	END
	ELSE IF(@USERNAME IS NOT NULL)
	BEGIN
		SELECT  * FROM POSTS WHERE AUTHOR=@USERNAME
	END
	
END;
GO
/****** Object:  StoredProcedure [dbo].[NEWPOST]    Script Date: 08/04/2025 17:08:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[NEWPOST]
@AUTHOR VARCHAR(50), @POSTCONTENT NVARCHAR(MAX)
AS
BEGIN
	
	INSERT INTO POSTS(AUTHOR,TITLE,COMMENT,MEDIATYPE,MEDIADATA,MEDIAFILENAME,POSTDATETIME, LATITUDE, LONGITUDE)
	SELECT @AUTHOR, JJ.title, JJ.comment, JJ.mediatype, JJ.media_b64,JJ.mediafilename,GETDATE(), JJ.latitude ,JJ.longitude 
	FROM OPENJSON(@POSTCONTENT,'$') WITH(
		title  VARCHAR(50),
		comment  VARCHAR(MAX),
		media_b64  NVARCHAR(MAX),
		mediatype  VARCHAR(100),
		mediafilename VARCHAR(300),
		latitude FLOAT,
		longitude FLOAT
	) JJ
	SELECT 1 AS ESITO
	
END;
GO
USE [master]
GO
ALTER DATABASE [GEOMEDIA] SET  READ_WRITE 
GO
