[16/03/2026 18:07]
Alberto:
USE [master]
GO
/****** Object:  Database [GEOMEDIA]    Script Date: 16/03/2026 18:04:08 ******/
CREATE DATABASE [GEOMEDIA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GEOMEDIA', FILENAME = N'/var/opt/mssql/data/GEOMEDIA.mdf' , SIZE = 270336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GEOMEDIA_log', FILENAME = N'/var/opt/mssql/data/GEOMEDIA_log.ldf' , SIZE = 270336KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [GEOMEDIA] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
	EXEC [GEOMEDIA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GEOMEDIA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ARITHABORT OFF 
GO
ALTER DATABASE [GEOMEDIA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GEOMEDIA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GEOMEDIA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GEOMEDIA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GEOMEDIA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GEOMEDIA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GEOMEDIA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GEOMEDIA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GEOMEDIA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GEOMEDIA] SET  ENABLE_BROKER 
GO
ALTER DATABASE [GEOMEDIA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GEOMEDIA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GEOMEDIA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GEOMEDIA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GEOMEDIA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GEOMEDIA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GEOMEDIA] SET RECOVERY FULL 
GO
ALTER DATABASE [GEOMEDIA] SET  MULTI_USER 
GO
ALTER DATABASE [GEOMEDIA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GEOMEDIA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GEOMEDIA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GEOMEDIA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GEOMEDIA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GEOMEDIA] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [GEOMEDIA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'GEOMEDIA', N'ON'
GO
ALTER DATABASE [GEOMEDIA] SET QUERY_STORE = ON
GO
ALTER DATABASE [GEOMEDIA] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [GEOMEDIA]
GO
/****** Object:  Table [dbo].[CATEGORIES]    Script Date: 16/03/2026 18:04:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORIES]
(
	[ID] [int] NULL,
	[TITLE] [varchar](50) NULL,
	[OWNERID] [int] NULL,
	[DESCRIPTION] [varchar](256) NULL,
	[IDC] [datetime] NULL,
	[DM] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HYPERMEDIA]    Script Date: 16/03/2026 18:04:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HYPERMEDIA]
(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FILEPATH] [varchar](256) NULL,
	[MEDIA_FILENAME] [varchar](300) NULL,
	[MEDIA_EXTENSION] [varchar](100) NULL,
	[POST_ID] [int] NULL,
	PRIMARY KEY CLUSTERED 
(
  [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOGS]    Script Date: 16/03/2026 18:04:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOGS]
(
	[ID] [int] NOT NULL,
	[MESSAGE] [nvarchar](1000) NULL,
	[SCOPE] [varchar](30) NULL,
	[16/03/2026 18:07]
	Alberto:
	[DATELOG] [datetime] NULL,
PRIMARY KEY CLUSTERED
	(
  [ID] ASC
)
	WITH
	(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
	/****** Object:  Table [dbo].[POSTS]    Script Date: 16/03/2026 18:04:08 ******/
	SET ANSI_NULLS ON
GO
	SET QUOTED_IDENTIFIER ON
GO
	CREATE TABLE [dbo].[POSTS]
	(
		[ID] [int] IDENTITY(1,1) NOT NULL,
		[AUTHOR_ID] [int] NULL,
		[TITLE] [varchar](50) NULL,
		[COMMENT] [varchar](max) NULL,
		[DC] [datetime] NULL,
		[DM] [datetime] NULL,
		[LATITUDE] [float] NULL,
		[LONGITUDE] [float] NULL,
		[EXCLUSIVITY] [bit] NULL,
		[EXCLUSITIVY_AREA_KM] [int] NULL,
		[EXCLUSIVITY_DATE_START] [datetime] NULL,
		[EXCLUSIVITY_DATE_END] [datetime] NULL,
		PRIMARY KEY CLUSTERED 
(
  [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
	/****** Object:  Table [dbo].[USERS]    Script Date: 16/03/2026 18:04:08 ******/
	SET ANSI_NULLS ON
GO
	SET QUOTED_IDENTIFIER ON
GO
	CREATE TABLE [dbo].[USERS]
	(
		[ID] [int] IDENTITY(1,1) NOT NULL,
		[USERNAME] [varchar](50) NULL,
		[PASSWORD] [nvarchar](256) NOT NULL,
		[EMAIL] [varchar](128) NULL,
		[NAME] [varchar](30) NULL,
		[SURNAME] [varchar](30) NULL,
		[DC] [datetime] NULL,
		[DM] [datetime] NULL,
		[PROFILE_PICTURE] [nvarchar](max) NULL,
		[LASTIP] [nvarchar](max) NULL,
		[OTPCODE] [varchar](6) NULL,
		PRIMARY KEY CLUSTERED 
(
  [ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
		UNIQUE NONCLUSTERED 
(
  [USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
	ALTER TABLE [dbo].[CATEGORIES] ADD  DEFAULT (getdate()) FOR [DM]
GO
	ALTER TABLE [dbo].[LOGS] ADD  DEFAULT (getdate()) FOR [DATELOG]
GO
	ALTER TABLE [dbo].[POSTS] ADD  DEFAULT (getdate()) FOR [DM]
GO
	ALTER TABLE [dbo].[USERS] ADD  DEFAULT (getdate()) FOR [DM]
GO
	ALTER TABLE [dbo].[USERS] ADD  DEFAULT (NULL) FOR [PROFILE_PICTURE]
GO
	ALTER TABLE [dbo].[CATEGORIES]  WITH CHECK ADD FOREIGN KEY([OWNERID])
REFERENCES [dbo].[USERS] ([ID])
GO
	ALTER TABLE [dbo].[HYPERMEDIA]  WITH CHECK ADD FOREIGN KEY([POST_ID])
REFERENCES [dbo].[POSTS] ([ID])
GO
	ALTER TABLE [dbo].[POSTS]  WITH CHECK ADD FOREIGN KEY([AUTHOR_ID])
REFERENCES [dbo].[USERS] ([ID])
GO
	/****** Object:  StoredProcedure [dbo].[AUTH_LOGIN]    Script Date: 16/03/2026 18:04:08 ******/
	SET ANSI_NULLS ON
GO
	SET QUOTED_IDENTIFIER ON
GO

	CREATE PROCEDURE [dbo].[AUTH_LOGIN]
		@JSON NVARCHAR(MAX)
	AS
	BEGIN

		DECLARE @USERNAME VARCHAR(50) = NULL,@EMAIL VARCHAR(128) = NULL, @PASSWORD NVARCHAR(256)

		SELECT @USERNAME=EMAIL, @EMAIL=EMAIL, @PASSWORD=PASSWORD
		FROM OPENJSON(@JSON,'$')WITH(
        EMAIL VARCHAR(128),
        PASSWORD NVARCHAR(256)
    )

		IF EXISTS (
        SELECT *
		FROM DBO.USERS
		WHERE (USERNAME=@USERNAME OR EMAIL=@EMAIL) AND [PASSWORD] = @PASSWORD
    )
    BEGIN
			SELECT 1 AS AUTH, ID AS UID, USERNAME, EMAIL, NAME, SURNAME
			-- PROFILE_PICTURE
			FROM USERS
			WHERE (USERNAME=@USERNAME OR EMAIL=@EMAIL)
		END
    ELSE
    BEGIN
			SELECT 0 AS AUTH, 'Invalid cretential' as MSG

		END



	END

GO
	/****** Object:  StoredProcedure [dbo].[AUTH_PSW_FORGOTTEN]    Script Date: 16/03/2026 18:04:08 ******/
	SET ANSI_NULLS ON
GO
	SET QUOTED_IDENTIFIER ON
GO
	CREATE PROCEDURE [dbo].[AUTH_PSW_FORGOTTEN]
		@JSON VARCHAR(MAX)
	AS
	BEGIN
		DECLARE @OTP VARCHAR(6) = (SELECT CONVERT(varchar(255),(SELECT CAST(RAND()*1000000 AS INT))))

		UPDATE U
  SET OTPCODE =@OTP
  FROM USERS U
			INNER JOIN OPENJSON(@JSON,'$')WITH(
    USERNAMEMAIL VARCHAR(128)
  ) J ON J.USERNAMEMAIL = U.EMAIL OR J.USERNAMEMAIL = U.USERNAME
		[16/03/2026 18:07]
		Alberto:
		SELECT @OTP AS OTP, U.EMAIL
		--IN ORDER TO SEND THE OTP CODE VIA EMAIL
		FROM USERS U
			INNER JOIN OPENJSON(@JSON,'$')WITH(
    USERNAMEMAIL VARCHAR(128)
  ) J ON J.USERNAMEMAIL = U.EMAIL OR J.USERNAMEMAIL = U.USERNAME

	END
GO
	/****** Object:  StoredProcedure [dbo].[AUTH_PSW_RESET]    Script Date: 16/03/2026 18:04:08 ******/
	SET ANSI_NULLS ON
GO
	SET QUOTED_IDENTIFIER ON
GO
	CREATE PROCEDURE [dbo].[AUTH_PSW_RESET]
		@JSON NVARCHAR(MAX)
	AS
	BEGIN
		UPDATE U
  SET PASSWORD=J.NEWPASSWORD
  FROM USERS U
			INNER JOIN OPENJSON(@JSON,'$')WITH(
      USERNAMEMAIL VARCHAR(128),
      NEWPASSWORD NVARCHAR(512),
      OTP VARCHAR(6)
  ) J ON (J.USERNAMEMAIL = U.EMAIL OR J.USERNAMEMAIL = U.USERNAME) AND J.OTP = U.OTPCODE

		IF @@ROWCOUNT>1
    SELECT 1 AS OK
  ELSE
  BEGIN
			SELECT 0 AS OK
		-- TODO: TO LOG THE REQUEST AS ATTACK/WRONG CODE
		END
	END
GO
	/****** Object:  StoredProcedure [dbo].[AUTH_SIGNIN]    Script Date: 16/03/2026 18:04:08 ******/
	SET ANSI_NULLS ON
GO
	SET QUOTED_IDENTIFIER ON
GO
	CREATE PROCEDURE [dbo].[AUTH_SIGNIN]
		@JSON NVARCHAR(MAX)
	AS
	BEGIN

		DECLARE @USERNAME VARCHAR(50), @EMAIL VARCHAR(128),@PASSWORD NVARCHAR(256),@NAME VARCHAR(30)=NULL, @SURNAME VARCHAR(30)=NULL

		SELECT @USERNAME=USERNAME, @EMAIL=EMAIL, @PASSWORD=PASSWORD, @NAME=NAME, @SURNAME=SURNAME
		FROM OPENJSON(@JSON,'$')WITH(
        USERNAME VARCHAR(50),
        EMAIL VARCHAR(128),
        PASSWORD NVARCHAR(256),
        NAME VARCHAR(30),
        SURNAME VARCHAR(30)
    )

		IF NOT EXISTS(
        SELECT *
		FROM USERS
		WHERE [EMAIL]=@EMAIL OR USERNAME = @USERNAME 
    )
    BEGIN

			DECLARE @OTP VARCHAR(6) = (SELECT CONVERT(varchar(255),(SELECT CAST(RAND()*1000000 AS INT))))
			INSERT INTO USERS
				(EMAIL, USERNAME, NAME, SURNAME, DC, DM,[PASSWORD],OTPCODE)
			VALUES(@EMAIL, @USERNAME, @NAME, @SURNAME, GETDATE(), GETDATE(), @PASSWORD, @OTP);

			EXEC AUTH_LOGIN @EMAIL=@EMAIL, @USERNAME=@USERNAME, @PASSWORD=@PASSWORD
		END
    ELSE
    BEGIN
			SELECT 0 AS AUTH, 'Username or email already taken' as MSG
		END
	END


GO
	/****** Object:  StoredProcedure [dbo].[HPMEDIA_MERGEFILE]    Script Date: 16/03/2026 18:04:08 ******/
	SET ANSI_NULLS ON
GO
	SET QUOTED_IDENTIFIER ON
GO

	CREATE procedure [dbo].[HPMEDIA_MERGEFILE]
		@FILESNAME_ATTACHED NVARCHAR(MAX),
		@POSTID INT
	AS
	BEGIN
		BEGIN TRY
        MERGE HYPERMEDIA AS target
            USING (
                SELECT *
		FROM OPENJSON(@FILESNAME_ATTACHED)
                WITH (
                    FILEPATH NVARCHAR(500),
                    MEDIA_FILENAME NVARCHAR(255),
                    MEDIA_EXTENSION NVARCHAR(50),
                    POST_ID INT
                )
            ) AS source
            ON  target.MEDIA_FILENAME = source.MEDIA_FILENAME
			AND target.MEDIA_EXTENSION = source.MEDIA_EXTENSION
			AND target.POST_ID = source.POST_ID

            WHEN NOT MATCHED BY TARGET THEN
                INSERT (FILEPATH, MEDIA_FILENAME, MEDIA_EXTENSION, POST_ID)
                VALUES (source.FILEPATH, source.MEDIA_FILENAME, source.MEDIA_EXTENSION, source.POST_ID)

            WHEN NOT MATCHED BY SOURCE
            AND target.POST_ID IN (
                SELECT POST_ID
		FROM OPENJSON(@FILESNAME_ATTACHED)
                WITH (POST_ID INT)
            )
            THEN DELETE;

        SELECT 1 AS OK
    END TRY
    BEGIN CATCH
        SELECT 0 AS OK, ERROR_MESSAGE() AS MSG
    END CATCH

	END
GO
	/****** Object:  StoredProcedure [dbo].[LOG_WRITE]    Script Date: 16/03/2026 18:04:08 ******/
	SET ANSI_NULLS ON
GO
	SET QUOTED_IDENTIFIER ON
GO

	CREATE PROCEDURE [dbo].[LOG_WRITE]
		@MESSAGE NVARCHAR(1000),
		@SCOPE VARCHAR(30) ='DEBUG'
	AS
	BEGIN
		INSERT INTO LOGS
			(MESSAGE,SCOPE)
		VALUES
			(@MESSAGE, @SCOPE)

	END
GO
	/****** Object:  StoredProcedure [dbo].[POST_DELETE]    Script Date: 16/03/2026 18:04:08 ******/
	SET ANSI_NULLS ON
GO
	SET QUOTED_IDENTIFIER ON
GO


	CREATE PROCEDURE [dbo].[POST_DELETE]
		@POSTID INT,
		@PASSWORD VARCHAR(128)
	AS
	BEGIN
[16/03/2026 18:07]
	Alberto:
	DELETE FROM POSTS  WHERE ID=@POSTID AND EXISTS (
        SELECT *
		FROM USERS
		WHERE ID = AUTHOR_ID AND PASSWORD=@PASSWORD
    )

	DECLARE @MSG NVARCHAR(1000)

	IF @@ROWCOUNT > 0
    BEGIN
		SELECT 1 AS OK
		SET @MSG =  CONCAT('DELETED POST', CAST(@POSTID AS VARCHAR(200)))
	END
    ELSE
    BEGIN
		SELECT 0 as OK
		SET @MSG =  CONCAT('CANNOT DELETE POST, WRONG PSW OR POSTID: ', CAST(@POSTID AS VARCHAR(200)), @PASSWORD)
	END

	EXEC LOG_WRITE @MESSAGE = @MSG, @SCOPE='POST_DELETE'


	END





GO
	/****** Object:  StoredProcedure [dbo].[POST_MEDIA_GET]    Script Date: 16/03/2026 18:04:08 ******/
	SET ANSI_NULLS ON
GO
	SET QUOTED_IDENTIFIER ON
GO
	CREATE PROCEDURE [dbo].[POST_MEDIA_GET]
		@POSTID INT
	AS
	BEGIN
		SELECT MEDIADATA
		FROM POSTS
		WHERE ID=@POSTID
	END


GO
	/****** Object:  StoredProcedure [dbo].[POST_MERGE]    Script Date: 16/03/2026 18:04:08 ******/
	SET ANSI_NULLS ON
GO
	SET QUOTED_IDENTIFIER ON
GO
	CREATE PROCEDURE [dbo].[POST_MERGE]
		@AUTHOR VARCHAR(50),
		@POSTCONTENT NVARCHAR(MAX)
	AS
	BEGIN
		BEGIN TRANSACTION T1
		BEGIN TRY

          DECLARE @Result TABLE (
			ID INT
        );

        MERGE INTO POSTS AS T
        USING (
            SELECT
			JJ.ID,
			JJ.AUTHOR_ID,
			JJ.TITLE,
			JJ.COMMENT,
			JJ.DC,
			JJ.DM,
			JJ.LATITUDE,
			JJ.LONGITUDE,
			JJ.EXCLUSIVITY,
			JJ.EXCLUSITIVY_AREA_KM,
			JJ.EXCLUSIVITY_DATE_START,
			JJ.EXCLUSIVITY_DATE_END
		FROM OPENJSON(@POSTCONTENT,'$') WITH(
                ID INT,
                AUTHOR_ID INT,
                TITLE VARCHAR(50),
                COMMENT VARCHAR(MAX),
                MEDIA_B64 NVARCHAR(MAX),
                MEDIATYPE VARCHAR(100),
                MEDIAFILENAME VARCHAR(300),
                LATITUDE FLOAT,
                LONGITUDE FLOAT,
                EXCLUSIVITY BIT,
                EXCLUSITIVY_AREA_KM INT,
                EXCLUSIVITY_DATE_START DATETIME2,
                EXCLUSIVITY_DATE_END DATETIME2,
                DC DATETIME2,
                DM DATETIME2
            ) JJ
        ) AS S
        ON T.ID = S.ID

        WHEN MATCHED THEN
            UPDATE SET
                    T.TITLE = ISNULL(S.TITLE,T.TITLE),
                    T.COMMENT = ISNULL(S.COMMENT,T.COMMENT),
                    T.DM = ISNULL(S.DM,T.DM),
                    T.LATITUDE = ISNULL(S.LATITUDE,T.LATITUDE),
                    T.LONGITUDE = ISNULL(S.LONGITUDE,T.LONGITUDE),
                    T.EXCLUSIVITY = ISNULL(S.EXCLUSIVITY,T.EXCLUSIVITY),
                    T.EXCLUSITIVY_AREA_KM = ISNULL(S.EXCLUSITIVY_AREA_KM,T.EXCLUSITIVY_AREA_KM),
                    T.EXCLUSIVITY_DATE_START = ISNULL(S.EXCLUSIVITY_DATE_START,T.EXCLUSIVITY_DATE_START),
                    T.EXCLUSIVITY_DATE_END = ISNULL(S.EXCLUSIVITY_DATE_END,T.EXCLUSIVITY_DATE_END)

        WHEN NOT MATCHED THEN
            INSERT (
                AUTHOR_ID, TITLE, COMMENT, DC, DM,
                LATITUDE, LONGITUDE, EXCLUSIVITY,
                EXCLUSITIVY_AREA_KM,
                EXCLUSIVITY_DATE_START,
                EXCLUSIVITY_DATE_END
            )
            VALUES (
                 S.AUTHOR_ID, S.TITLE, S.COMMENT, S.DC, S.DM,
                S.LATITUDE, S.LONGITUDE, S.EXCLUSIVITY,
                S.EXCLUSITIVY_AREA_KM,
                S.EXCLUSIVITY_DATE_START,
                S.EXCLUSIVITY_DATE_END
            )

        OUTPUT inserted.ID
        INTO @Result;

        COMMIT TRANSACTION T1;
        SELECT ID AS ID, 1 AS OK
		FROM @Result;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION T1;
        SELECT -1 AS ID, 0 AS OK, ERROR_MESSAGE() AS MSG
    END CATCH
	END;


GO
	/****** Object:  StoredProcedure [dbo].[POSTS_GET]    Script Date: 16/03/2026 18:04:08 ******/
	SET ANSI_NULLS ON
GO
	SET QUOTED_IDENTIFIER ON
GO
	CREATE PROCEDURE [dbo].[POSTS_GET]
    @USERNAME VARCHAR(50)=NULL
-- @LATITUDE FLOAT=NULL, @LONGITUDE FLOAT=NULL, @USERNAME VARCHAR(50)=NULL
[16/03/2026 18:07]
	Alberto:
	AS
	BEGIN



		IF(@USERNAME IS NULL OR @USERNAME='NULL')
  BEGIN
							SELECT ID, AUTHOR, TITLE, COMMENT, MEDIATYPE, POSTDATETIME, LATITUDE, LONGITUDE, MEDIAFILENAME, IS_EXCLUSIVE, AREA_KM
				FROM POSTS
				WHERE DATETIME_AVAILABILITY IS NULL
			UNION
				SELECT ID, AUTHOR, TITLE, COMMENT, MEDIATYPE, POSTDATETIME, LATITUDE, LONGITUDE, MEDIAFILENAME, IS_EXCLUSIVE, AREA_KM
				FROM POSTS
				WHERE DATETIME_AVAILABILITY IS NOT NULL AND GETDATE()<DATETIME_AVAILABILITY
		END
  ELSE IF(@USERNAME IS NOT NULL)
  BEGIN
			SELECT *
			FROM POSTS
			WHERE AUTHOR=@USERNAME
		END

	END;


GO
	/****** Object:  StoredProcedure [dbo].[PROFILE_EditInfo]    Script Date: 16/03/2026 18:04:08 ******/
	SET ANSI_NULLS ON
GO
	SET QUOTED_IDENTIFIER ON
GO
	CREATE PROCEDURE [dbo].[PROFILE_EditInfo]
		@JSON NVARCHAR(MAX)
	AS
	BEGIN
		UPDATE U
  SET
  U.USERNAME  = ISNULL(JJ.USERNAME , U.USERNAME)
  ,U.PASSWORD  = ISNULL(JJ.PASSWORD ,U.PASSWORD)
  ,U.EMAIL  = ISNULL(JJ.EMAIL ,U.EMAIL)
  ,U.NAME  = ISNULL(JJ.NAME ,U.NAME)
  ,U.SURNAME  = ISNULL(JJ.SURNAME ,U.SURNAME)
  ,U.PROFILE_PICTURE  = ISNULL(JJ.PROFILE_PICTURE ,U.PROFILE_PICTURE)
  ,U.DM = GETDATE()
  FROM USERS U
			INNER JOIN OPENJSON(@JSON,'$') WITH(
    ID INT
    ,USERNAME VARCHAR(50)
    ,PASSWORD NVARCHAR(512)
    ,EMAIL VARCHAR(128)
    ,NAME VARCHAR(30)
    ,SURNAME VARCHAR(30)
    ,PROFILE_PICTURE NVARCHAR(MAX)
  ) JJ ON JJ.ID = U.ID

		SELECT *
		FROM USERS
		WHERE ID = (
    SELECT JSON_VALUE(@JSON,'ID')
  )

	END
GO
	/****** Object:  StoredProcedure [dbo].[PROFILE_GetPFP]    Script Date: 16/03/2026 18:04:08 ******/
	SET ANSI_NULLS ON
GO
	SET QUOTED_IDENTIFIER ON
GO
	CREATE PROCEDURE [dbo].[PROFILE_GetPFP]
		@JSON NVARCHAR(MAX)
	AS
	BEGIN
		SELECT
			PROFILE_PICTURE
		FROM DBO.USERS
		WHERE USERNAME = JSON_VALUE(@JSON, '$.USERNAME')

	END
GO
	USE [master]
GO
	ALTER DATABASE [GEOMEDIA] SET  READ_WRITE 
GO